version: 2
updates:
  # Define updates for Python dependencies using pip
  - package-ecosystem: "pip"
    # Folders with requirements.txt file
    directory: "/financial_assistant"
    schedule:
      # Check for updates every day
      interval: "daily"
      # Optional: set a specific time for daily updates
      time: "12:00"
      # Optional timezone definition
      timezone: "Etc/UTC"
    commit-message:
      prefix: "pip dependency update"
    # Optional: Use labels on PRs for easier sorting/filtering
    labels:
      - "dependencies"
    groups:
      core-dependencies:
        # Applies the group rule to version updates
        applies-to: version-updates
        # Define patterns to include dependencies in the group (based on dependency name)
        patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "minor"
          - "patch"
      # All the Python packages (excluding core dependencies)
      other-packages:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "minor"
          - "patch"
