version: 2
updates:
  # Define updates for Python dependencies using pip
  - package-ecosystem: "pip"
    # Folders with requirements.txt file
    directories:
      # Main repository
      - "/"
      # First degree folders
      - "/benchmarking"
      - "/bundle_jump_start"
      - "/data_extraction"
      - "/document_comparison"
      - "/e2e_fine_tuning"
      - "/enterprise_knowledge_retriever"
      - "/eval_jumpstart"
      - "/financial_assistant"
      - "/fine_tuning_embeddings"
      - "/fine_tuning_sql"
      - "/funcion_calling"
      - "/image_search"
      - "/multimodal_knowledge_retriever"
      - "/post_call_analysis"
      - "/prompt_engineering"
      - "/sambanova_scribe"
      - "/search_assistant"
      - "/tests"
      - "/web_crawled_data_retriever"
      # Second degree repositories
      - "/utils/*"
    schedule:
      # Check for updates every day
      interval: "daily"
      # Optional: set a specific time for daily updates
      time: "15:00"
      # Optional timezone definition
      timezone: "Etc/UTC"
    commit-message:
      prefix: "pip dependency update"
    # Optional: Use labels on PRs for easier sorting/filtering
    labels:
      - "dependencies"
    groups:
      # All the Python core dependencies: minor + patch
      core-dependencies:
        applies-to: version-updates
        patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "minor"
          - "patch"
      # All the other Python packages: minor + patch
      other-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "minor"
          - "patch"
      # All the Python core dependencies: major
      core-dependencies:
        applies-to: version-updates
        patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "major"
      # All the other Python packages: major
      other-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "major"
