version: 2
updates:
  # Define updates for Python dependencies using pip
  - package-ecosystem: "pip"
    # Folders with requirements.txt file
    directories:
      - "/benchmarking"
      - "/financial_assistant"
      - "/funcion_calling"
      - "/multimodal_knowledge_retriever"
      - "/search_assistant"
    schedule:
      # Check for updates every day
      interval: "daily"
      # Optional: set a specific time for daily updates
      time: "15:00"
      # Optional timezone definition
      timezone: "Etc/UTC"
    commit-message:
      prefix: "pip dependency update"
    # Optional: Use labels on PRs for easier sorting/filtering
    labels:
      - "dependencies"
    groups:
      # All the Python core dependencies: minor + patch
      core-dependencies:
        applies-to: version-updates
        patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "minor"
          - "patch"
      # All the other Python packages: minor + patch
      other-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "minor"
          - "patch"
      # All the Python core dependencies: major
      core-dependencies:
        applies-to: version-updates
        patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "major"
      # All the other Python packages: major
      other-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "llama-index*"
          - "langchain*"
          - "crewai*"
          - "pandasai"
          - "pydantic"
          - "python-dotenv"
          - "streamlit*"
          - "st-pages"
          - "sseclient-py"
          - "torch"
        update-types:
          - "major"
