synthetic:
  model_configs_path: '~/github_repos/ai-starter-kit/benchmarking/benchmarking_studio/model_configs.csv'
  llm_api: 'sncloud'
  output_files_dir: '~/github_repos/benchmarking_tracking_tests/logs/output_files'
  consolidated_results_dir: '~/github_repos/benchmarking_tracking_tests/consolidated_results'
  timeout: 3600
  time_delay: 0
  ratio: 1