synthetic:
  model_configs_path: '~/ai-starter-kit//benchmarking/benchmarking_studio/model_configs_example.csv'
  llm_api: 'sncloud'
  output_files_dir: '~/ai-starter-kit/benchmarking/data/benchmarking_tracking_tests/logs/output_files'
  consolidated_results_dir: '~/ai-starter-kit/benchmarking/data/benchmarking_tracking_tests/consolidated_results'
  timeout: 3600
  time_delay: 0
  ratio: 1