services:
  backend:
    build:
      context: ./
      dockerfile: web_app/backend/Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ../financial_agent_crewai:/app/financial_agent_crewai
    env_file:
      - ./web_app/backend/.env
    command: uvicorn financial_agent_crewai.web_app.backend.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./web_app/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./web_app/frontend/src:/app/src
      - /app/node_modules
    env_file:
      - ./web_app/frontend/.env
    command: yarn dev --host
  
  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 6G
        reservations:
          cpus: '0.5'
          memory: 2G
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --save 60 1000
